%% DEMO_PRETRAINING
%
% Training MDNet models.
%
% Hyeonseob Nam, 2015
%

clear;
close all;
clc;
run(fullfile(fileparts(mfilename('fullpath')), ...
  '..','matconvnet','matlab', 'vl_setupnn.m'));
addpath('pretraining');
addpath('tracking');
addpath('utils');
addpath('pretraining/bbox_functions');
% Prepare a CNN model for learning MDNet.
dst_model = fullfile('models', 'mdnet_roi_init_pw_sub3_bbox.mat');
mdnet_roi_prepare_model('src_model', './models/imagenet-vgg-m-conv1-3.mat',...
     'dst_model', dst_model,'subdivision', 3);

%% Training MDNet using the sequences from {VOT13,14,15}-{OTB100}
%for experiments on OTB
%dst_model = fullfile('data','exp_vot-otb_start','net-epoch-3.mat');
 mdnet_roi_pretrain('seqsList',...
     {struct('dataset','vot2013','list','pretraining/seqList/vot13-otb.txt'),...
     struct('dataset','vot2014','list','pretraining/seqList/vot14-otb.txt'),...
     struct('dataset','vot2015','list','pretraining/seqList/vot15-otb.txt')},...
     'netFile', dst_model,...
     'expDirName', 'exp_vot-otb_start_search_region_seven',... 
      'imdbDir', fullfile('models','data_vot-otb'),...
      'imdbName', 'roi_imdb_start_region_seven',...
      'modelPath', fullfile('models', 'net-deployed_vot-otb_start_search_region_seven.mat'), ...
      'intemidiate', false, 'hardnegmining', false, 'gpus', [2], 'piecewise', false, 'visualize', false...
      );

%% Training MDNet using the sequences from {OTB}-{VOT14}
% for experiments on VOT14
% mdnet_roi_pretrain('seqsList',...
%     {struct('dataset','otb','list','pretraining/seqList/otb-vot14.txt')},...
%     'netFile', dst_model,...
%     'expDirName', 'exp_otb-vot14_sub3_oneas_large_nopw',... 
%     'imdbDir', fullfile('models','data_otb-vot14'),...
%     'modelPath', fullfile('models', 'net-deployed_otb-vot14_sub3_oneas_large_nopw.mat')...
%     );
%dst_model = fullfile('data','exp_sub3_oneas_large_nopw','net-epoch-3.mat');
% mdnet_roi_pretrain('seqsList',...
%     {struct('dataset','otb','list','pretraining/seqList/otb-vot15.txt')},...
%     'netFile', dst_model,...
%     'expDirName', 'exp_otb-vot15_sub3_oneas_large_nopw',... 
%     'imdbDir', fullfile('models','data_otb-vot15'),...
%     'modelPath', fullfile('models', 'net-deployed_otb-vot15_sub3_oneas_large_nopw.mat')...
%     );
% % for experiments on VOT14
%dst_model = fullfile('data','exp_val005_pw_sbbox_relu_new','net-epoch-5.mat');
%
%mdnet_roi_pretrain('seqsList',...
%    {struct('dataset','otb','list','pretraining/seqList/otb-vot14.txt')},...
%    'netFile', dst_model,...
%    'expDirName', 'exp_val005_pw_sbbox_relu_new',... 
%    'imdbDir', fullfile('models','data_otb-vot14'),...
%    'modelPath', fullfile('models', 'net-deployed_shared_bbox_relu_new_start.mat')...
%    );
%
%
%% Training MDNet using the sequences from {OTB}-{VOT15}
% for experiments on VOT15
% mdnet_roi_pretrain('seqsList',...
%     {struct('dataset','otb','list','pretraining/seqList/otb-vot15.txt')},...
%     'outFile', fullfile('models','mdnet_otb-vot15_new.mat'),...
%     'imdbDir', fullfile('models','data_otb-vot15'));
